pipeline {
    agent {
        docker {
            image 'node:18'
            args '-u root'
        }
    }

    stages {

        stage('Say Hello') {
            steps {
                echo "Hello DevOps from Jenkins Pipeline!"
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('simple-node-app') {
                    sh 'npm install'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('simple-node-app') {
                    sh 'npm test'
                }
            }
        }

    }
}

