pipeline {
    agent {
        docker {
            image 'node:18'
            args '-u root'
        }
    }

    stages {
        stage('Say Hello') {
            steps {
                echo "Hello DevOps from Jenkins Pipeline (Running inside Docker Container)!"
            }
        }
    }
}
